version: '3.3'
services:
  transmission-openvpn:
    volumes:
      - ~/.docker/volumes/transmission:/data/transmission-home
      - ~/Downloads/incoming:/downloads/incoming
      - ~/Downloads/watching:/downloads/watching
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn:latest-armhf
    dns:
      - 1.1.1.1
      - 1.0.0.1

  sickgear:
    image: linuxserver/sickgear
    container_name: sickgear
    environment:
      - TZ=Europe/Amsterdam
      - PUID=0
      - PGID=0
    volumes:
      - ~/.docker/volumes/sickgear:/config
      - ~/Downloads/completed/Series:/tv
      - ~/Downloads/incoming:/downloads/incoming
      - ~/Downloads/watching:/downloads/watching
    ports:
      - 8081:8081
    restart: unless-stopped
    links:
      - transmission-openvpn
    dns:
      - 1.1.1.1
      - 1.0.0.1
